package com.reason.games.farm.enums;

public enum Info {
    
    CHOOSELANGUAGE,
    ENLANG,
    RULANG,
    LANGINTERFACE,
    
    WELCOMETEXT,
    INTERFACETEXT,
    HELLOTEXT,
    
    INTERFACESEESTATUSCOLUMN,
    INTERFACEMAKEPLANTATION,
    INTERFACEGETPROFIT,
    
    CELLSTATUSRULES,
    CELLHASSTATUS,
    CELLHASSTATUSREADY,
    CELLNOTSTATUS,
    CELLCHOOSERULES,
    ARRAYOFPLANTS,
    CALLCOLUMNINFO,
    NOPLANT,
    CELLNUMBER,
    CHOOSECELL,
    CELLNOTFREE,
    PLANTSUCCESSFUL,
    STATUSMATURES,
    STATUSREADY,
    STATUSHALFREADY,
    NOFREECELLS,
    
    CHOOSEPLANTRULES,
    CHOOSEPLANT,
    CHOOSECELLTOPLANT,
    WRONGCELL,
    WRONGNAMEPLANT,
    CALLMAKEPLANTATION,
    BALANCE,
    GETALLPROFIT,
    INCOME,
    
    
    HARVESTRULES,
    TOHARVEST,
    PLANTISNOTREADY,
    CALLHARVEST,
    NOREADYPLANT,
    PROFITISGOT,
    
    
    NOTHAVEMONEYANYPLANT,
    DONTHAVEMONEY,
    WRONGINPUT,
    BACK,
    LEFT,
    RIGHT,
    WRONGINPUTNAME,
    LANG,
    GAMERULES
}
